# [build-system]
# requires = ["setuptools >= 61.0"]
# build-backend = "setuptools.build_meta"

[project]
name = "medmeld-messages"
version = "0.1.0"
dependencies = ["uagents"]
requires-python = ">= 3.8"
